import Link from 'next/link'
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <nav style={{ padding: 16, margin: 8 }}>
          <Link style={{ padding: "0 10px 0 0" }} href="/">Home</Link>
          <Link style={{ padding: "0 10px 0 0" }} href="/postingan">Postingan</Link>
        </nav>
        <hr />
        <div>{children}</div>
      </body>
    </html>
  )
}